fix: scripts/get-task-fuzzy-duration.py: Account for long running tasks
redhat-performance/satperf pull request #223
Opened 2023-03-10 17:22 UTC by pablomh

Instead of waiting an arbitrary amount of time, look for tasks that doesn't seem to progress in a certain amount of time (in this case: 10 minutes).

2023-03-11 06:30 UTC, jhutar commented on scripts/get-task-fuzzy-duration.py
> +    timeout_minutes = 10
Could you repurpose `args.timeout` for `timeout_minutes` (and change default)?

2023-03-11 06:34 UTC, jhutar commented on scripts/get-task-fuzzy-duration.py
> +    parent_task = get_json(
What about changing a logic of that `while True` internals so we do not need two of this `get_json(...)` calls here?

2023-03-11 06:35 UTC, jhutar requested changes
Feel free to merge even in this state. Comments I made are not important.

2023-03-12 21:34 UTC, merged

2023-03-12 21:56 UTC, pablomh commented
I included by mistake this commit in a bunch with other. I'll integrate your comments in a subsequent revision :/